### ISSUE TITLE
bareboximd doesn't have -c flag

### ISSUE THREAD

**Issue by hmenn** [phytec/meta-phytec#1]
I'm working on dunfell branch and using barebox 2018.11.0.

According to [this](https://git.phytec.de/meta-phytec/commit/?h=dunfell&id=ec2d1cc8c14adf0ff5f3b506ccdfeeace60d32d1) commit crc checksum was added into the metadata but -C flag is only available for newer versions.

[2018.11.0_doc](https://www.barebox.org/doc/2018.11.0/commands/info/imd.html?highlight=imd)
[2020.11.0_doc](https://www.barebox.org/doc/latest/commands/info/imd.html?highlight=imd)

**Comment by smk-embedded** [comment]
Thanks for the report!
The 2018 barebox with AM335x is currently not supported on dunfell. As soon as we add AM335x support, we will update the barebox on dunfell to a newer version. The easiest way to see that is in meta-yogurt. As long as there is no release for a SoC, like AM335x on a branch, we update receipts. After the first release on a branch, it is considered stable, and we only update stable patches.

**Comment by smk-embedded** [comment]
We moved the imd command, so this issue is fixed with commit:
9b686e9839f64b032632405e04204000cdeec722
