### ISSUE TITLE
am335x dev board which machine to use

### ISSUE THREAD

**Issue by nandra** [phytec/meta-phytec#10]
Hello, I have dev kit PCM953 and am335x module PCM-051 (on module is written 1358.3) I would like to build yocto but cannot somehow identify which machine should I use for this machine type. Can you please give me some hint which machine to use? Thanks

**Comment by tremmet** [comment]
Hello Marek,
yes there are a lot of machines which makes it quite confusing.
Correct machine in your case should be "phycore-am335x-1"

Regards,
Teresa

**Comment by nandra** [comment]
@tremmet perfect. Many thanks.
