### ISSUE TITLE
Problem in phytec-am335x for bareboxenv tool

### ISSUE THREAD

**Issue by M-Inamullah** [phytec/meta-phytec#15]
Hi All,
I am working on phytec-am335x. I want to modify or change the environment variables so i enable the **build bareboxenv tool for target** from menuconfig of barebox but after that when i tried to bitbake the barebox it gave following  error

```
/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/scripts/bareboxenv.c:20:10: fatal error: stdio.h: No such file or directory
|    20 | #include <stdio.h>
|       |          ^~~~~~~~~
| compilation terminated.
| make[3]: *** [/media/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/scripts/Makefile:58: scripts/bareboxenv-target] Error 1
| make[2]: *** [/media/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/Makefile:426: scripts] Error 2
| make[1]: *** [Makefile:123: all] Error 2
| make: *** [Makefile:24: __sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.

```

I also install the pakages  libc6-dev  also the build-essential again but still same error. 
Can anyone guide me to resolve this issue 

Thanks

**Comment by svlstriker** [comment]
Hi,
could you please add some more information about your build-environment and setup?
- Which OS do you use?
- Which BSP do you build exactly?
- What are your changes exactly?
- Did you try a clean build before your changes?

Regards

**Comment by smk-embedded** [comment]
Did you have a look at the receipt barebox-targettools? We separated the gcc settings for baremetal compile and userspace compile.

**Comment by M-Inamullah** [comment]
> Hi, could you please add some more information about your build-environment and setup?
> 
> * Which OS do you use?
> * Which BSP do you build exactly?
> * What are your changes exactly?
> * Did you try a clean build before your changes?
> 
> Regards


Thanks for your reply @smk-embedded @svlstriker 

Basically the main concern is to **modify or change the enevironment variables** of barebox from `rootfs` as in case of U-BOOT there is no direct getenv/setenv  functionality so I found that there is tool named bareboxenv_tool can be used to modify the variables. is there any other method by which i can modify or change the variables please guide me.


I am basically using **phytec am335x** board. In which kernel is **linux-mainline** and the bootloader is **barebox.** .when i tried to enable the Bareboxenv tool from menuconfig shown

```
[*] build bareboxenv tool for target

```
After enabling it when tried to bitbake barebox faced the error

```
/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/scripts/bareboxenv.c:20:10: fatal error: stdio.h: No such file or directory
|    20 | #include <stdio.h>
|       |          ^~~~~~~~~
| compilation terminated.
| make[3]: *** [/media/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/scripts/Makefile:58: scripts/bareboxenv-target] Error 1
| make[2]: *** [/media/junaid/1-TB-HDD/forklifter-data/build_fork/tmp/work/phycore_am335x_4-poky-linux-gnueabi/barebox/2018.11.0-phy3-r7.0/git/Makefile:426: scripts] Error 2
| make[1]: *** [Makefile:123: all] Error 2
| make: *** [Makefile:24: __sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.

```
When i goto the directory where bareboxenv.c file exits there is include directory there is no stdio.h library in it.

**Comment by smk-embedded** [comment]
The bareboxenv tool is the right tool, but that is not how you would add it to your image. Instead try running:
$ bitbake barebox-targettools
This will build the tool. If you want to install the packaged tool into the image for dunfell:
`IMAGE_INSTALL_append = " barebox-targettools"`

**Comment by M-Inamullah** [comment]
Thanks @smk-embedded  for providing the solution 
Issue resolved successfully that's why closing this issue 
Thanks again
