### ISSUE TITLE
Error: Could not inherit file classes/image-types-partup.bbclass

### ISSUE THREAD

**Issue by S4mw1s3** [phytec/meta-phytec#17]
Hello,

our build fails due to error `Could not inherit file classes/image-types-partup.bbclass`. I could not find this file anywhere. Is this file perhaps missing?

**Comment by svlstriker** [comment]
Hi,
thank you for indicating this issue.
We just saw, that we have a new dependency on meta-ampliphy, which we do not want to have.
For now your build should work again, if you remove/revert the following patches from meta-phytec:

commit 1862444fb8f11fcf20319726bd9d11665ff790b7
conf: machine: partup-layout-config: Add package dependency

commit d76c8654ab53a7719032e616e8ebb9b20a4a09a2
conf: machine: partup-layout-config: Use append syntax for input files

commit 503991e6411a714d1219e38a1359e36f23da7cfd
conf: machine: phyimx8: Enable partup image type

commit 298b30a6d422b32479528dfb1676a3a2248f5ae2
conf: machine: phyimx6ul: Enable partup image type

commit 8d476ef7f7f93b364ca06a2684555d46ab891a71
conf: machine: phyimx6: Enable partup image type

commit 4beae7a4b52c2ee6e1eda5fd2875849b74f8eadd
conf: machine: Add partup layout configuration

We are sorry for this issue and are working on a fix.

**Comment by svlstriker** [comment]
The issue has been fixed now, so there is no workaround needed anymore.
