### ISSUE TITLE
phygate-tauri-l-imx8mm eth0 and eth1 are switched 

### ISSUE THREAD

**Issue by duncan-dommerdich-beebryte** [phytec/meta-phytec#21]
Hi,

In our phyGATE Tauri-L a ticket recently arrived with the following remarks :

> Test case: 
> 
>     - configure both eth 0 and eth1 with DHCP
> 
>     - connect only eth0 to a DHCP server
> 
>     - connect only eth1 to a DHCP server
> 
> Result: 
> 
>     - eth0 on port LAN2 with MAC address 1
> 
>     - eth1 on port LAN1 with MAC address 2

I've checked the following:

- no udev rule set the interface name
- ethernet0 alias is set in arch/arm64/boot/dts/freescale/imx8mm.dtsi, I've tried to change to ethernet1 nothing changed

If you need any further information, don't hesitate to ask :smiley:

**Comment by tremmet** [comment]
@duncan-dommerdich-beebryte Which BSP/kernel/yocto version are you using?

**Comment by duncan-dommerdich-beebryte** [comment]
thanks for the rapid answer, here are my checkout:

- poky: kirkstone-4.0.16 commit: 54af8c5e80ebf63707ef4e51cc9d374f716da603
- meta-oe: commit: 79a6f60dabad9e5b0e041efa91379447ef030482
- kernel : 5.15
- meta-freescale: commit: c82d4634e7aba8bc0de73ce1dfc997b630051571
- meta-phytec: tag: BSP-Yocto-NXP-i.MX8MM-PD23.1.0
- meta-arm: yocto-4.0.3
- meta-imx-bsp: rel_imx_5.15.71_2.2.2

**Comment by tremmet** [comment]
@duncan-dommerdich-beebryte Thank you. We will check internally.

**Comment by gportay** [comment]
> @gportay Yes, this is how it looks for me, too. I am waiting for feedback of the team that created the housing if there is anything behind this. As we mostly work without housing, we did not notice our self's.
> 
> And yes the MAC of the fec interface inside of the i.MX8MM is stored in FUSEs and the Intel one as an internal EEPROM.

Thanks.

**Comment by tremmet** [comment]
@duncan-dommerdich-beebryte The LAN[1|2] numbering of the housing was independently done from schematics and BSP. It was created based on user expectations from top to bottom. See: 
https://www.phytec.de/cdocuments/?doc=woHCFw#HardwareandBSPReferenceManualphyGATETauriLi-MX8MMiniKitL1028e-A1-ElectricalConnection

What are your requirements here?

**Comment by gportay** [comment]
> @duncan-dommerdich-beebryte The LAN[1|2] numbering of the housing was independently done from schematics and BSP. It was created based on user expectations from top to bottom.

Does the **LAN1** expect to use the **MAC-ID-1**? and **LAN2**/**MAC-ID-2** or the numbering is not correlated?

**Comment by tremmet** [comment]
> > @duncan-dommerdich-beebryte The LAN[1|2] numbering of the housing was independently done from schematics and BSP. It was created based on user expectations from top to bottom.
> 
> Does the **LAN1** expect to use the **MAC-ID-1**? and **LAN2**/**MAC-ID-2** or the numbering is not correlated?

It is directly the inverse. 

MAC-ID-1 (i.MX8MM FEC) ->  ETH0_CON -> X30 -> LAN2
MAC-ID-2 (Intel IGB) -> ETH1_CON  -> X29 -> LAN1

**Comment by tremmet** [comment]
@gportay I agree. Thank you for your feedback. I asked the colleagues to improve the documentation about the ethernet interface naming.
