### ISSUE TITLE
bootenv.txt with '#' ?

### ISSUE THREAD

**Issue by vermaete** [phytec/meta-phytec#23]
Hi,

When using the precompiled image to boot the imx8mp on the phyboard to run the gstreamer application with the ISP demo, the bootenv.txt has this content:

`overlays=conf-imx8mp-phyboard-pollux-peb-av-10.dtbo#conf-imx8mp-phyboard-pollux-isp-csi1.dtbo#conf-imx8mp-phyboard-pollux-isi-csi1.dtbo#conf-imx8mp-phyboard-pollux-vm016-csi1.dtbo`

However, when trying to build the image myself it only has:
`overlays=conf-imx8mp-phyboard-pollux-peb-av-10.dtbo`

And checking the recipe [phytec-bootenv.bb](https://github.com/phytec/meta-phytec/blob/master/recipes-bsp/bootenv/phytec-bootenv.bb) it looks like a space is used to separate the elements in the list.
What - at lease for me- did not booted.
With the '#' as separator the overlays are loaded fine in the FIT image.

br

**Comment by BHahn42618** [comment]
Hi,
As we switched to fitImage boot for the new PD24.1.0 imx8mp NXP release, the bootm command in U-Boot is now used to boot fitImages. The U-Boot wants all the devicetree configurations separated by '#' appended to that command. That is why the overlays variable looks different now in the bootenv.txt. This is described for example here in the BSP documentation:
https://phytec.github.io/doc-bsp-yocto/bsp/imx8/imx8mp/pd24.1.0_nxp.html#set-overlays-variable

**Comment by BHahn42618** [comment]
Hi,
As we switched to fitImage boot for the new PD24.1.0 imx8mp NXP release, the bootm command in U-Boot is now used to boot fitImages. The U-Boot wants all the devicetree configurations separated by '#' appended to that command. That is why the overlays variable looks different now in the bootenv.txt. This is described for example here in the BSP documentation:
https://phytec.github.io/doc-bsp-yocto/bsp/imx8/imx8mp/pd24.1.0_nxp.html#set-overlays-variable

As you noticed, the phytec-bootenv.bb needs some updating to that new style. I sent a patch internally for that and hope it will be public soon.

As for the differences between the prebuilt and the self built image. Which prebuilt image did you download? A link or something would be nice. And did you build the same image with the same distro name in the local.conf as the prebuilt?
The additional overlays are some camera related overlays, that do not get applied for other images (bsp. qt6demo or headless image).

**Comment by vermaete** [comment]
@BHahn42618 
Thanks for your clear an fast answer.
The release I have download was:
`ampliPHY Vendor xwayland (Phytec Vendor Distribution) BSP-Yocto-NXP-i.MX8MP-PD24.1.0 phyboard-pollux-imx8mp-3`

And this one was working out of the box.  So with a '#' as separator 

The one I was building myself is:
`ampliPHY Vendor xwayland (Phytec Vendor Distribution) BSP-Yocto-NXP-i.MX8MP-PD24.1-rc2-devel phyboard-pollux-imx8mp-3`
Building it with 'phytec-vision-image`.  And some small modifications to have it working in a air-gapped-network.
And this one did have ' ' as separator.  After appending to the recipe to have it with '#', all was working fine.
