### ISSUE TITLE
Invalid linux-mainline_5.10.%.bbappend

### ISSUE THREAD

**Issue by S4mw1s3** [phytec/meta-phytec#4]
Current hardknott branch (and I guess master as well) breaks our yocto builds with the following error:

```
ERROR: No recipes in default available for:
.../sta_phycore/sources/poky/../meta-phytec/recipes-kernel/linux/linux-mainline_5.10.%.bbappend
```

This commit e12aff1c615a8e90cae0cb347ef2eef2fcfeac21 introduced linux-mainline_5.10.%.bbappend.
I did a search and could not find any linux-mainline_5.10.*.bb file. Is it supposed to be in another layer that we are missing?

**Comment by smk-embedded** [comment]
Issue should be fixed now. We include a robot layer for nightly builds: https://github.com/phytec/meta-fresh
meta-fresh gets the kernel updates earlier. We do not have a release on hardknott yet, so the build without meta-fresh has not been triggered. Thats why the build error was not catched by us yet.

**Comment by S4mw1s3** [comment]
I confirm this is fixed. Thanks!
