### ISSUE TITLE
u-boot-imx_2020.04_2.3.2-phy7.bb from dunfell is not buildable against poky/oe-core 

### ISSUE THREAD

**Issue by mlilien** [phytec/meta-phytec#8]
```
ERROR: Nothing PROVIDES 'python' (but /yocto-build/meta-phytec/recipes-bsp/u-boot/u-boot-imx_2020.04_2.3.2-phy7.bb DEPENDS on or otherwise requires it). Close matches:
  python3
  python3-py
  python3-sh
```
The used poky version tag is  "yocto-3.1.11". Am I missing a dependency?

**Comment by mlilien** [comment]
My attempts look promising so far. Changes I had to do for a polis device: 
```
PREFERRED_PROVIDER:virtual/kernel ?= "linux-imx"
DEPENDS:remove:pn-u-boot-imx = " python"
DEPENDS:append:pn-u-boot-imx = " bc-native python3"
ATF_MACHINE_NAME:pn-imx-boot = "bl31-imx8mm.bin"
ATF_MACHINE_NAME:pn-imx-boot-phytec = "bl31-imx8mm.bin"
PLATFORM:pn-imx-atf = "imx8mm"
SOC_TARGET:pn-imx-boot = "iMX8MM"
SOC_TARGET:pn-imx-boot-phytec = "iMX8MM"
IMXBOOT_TARGETS = "flash_evk"
```
I copied the `imx-atf` and `imx-mkimage`  from `dynamic-layers/fsl-bsp-release`. I had to remove the dependency to `imx-seco` in the `imx-mkimage` recipe.

Currently I'm adapting u-boot-imx for my own boot scripts. As far as I can see, at least I don't really need the `fsl-bsp-release` layer.

One more thing: I have a a phytec polis device which doesnt match the `MACHINE` configuration exactly. I use `phyboard-polis-imx8mm-4.conf` for a "PB-02820-001.A1" device. Can you confirm that I use the correct one? The description of `phyboard-polis-imx8mm-4.conf` states that it is for PB-02820.A2 with 16GB emmc. I seem to have a 8GB emmc.

**Comment by tremmet** [comment]
We have a initial Yocto master branch setup for i.MX8MP where we also don't use the fsl-bsp-release layer by moving the imx-atf and imx-mkimage to dynamic-layers/freescale-layer. So this has been done for newer branches of meta-phytec.

Using phyboard-polis-imx8mm-4.conf is save with PB-02820-001.A1. eMMC size is don't care for the machine. The first prototypes had 16GB. We are aware that the description is outdated and working on an update. At least for the upcoming hardknott based release.

Regards,
Teresa

**Comment by smk-embedded** [comment]
no updates for some time, if you still have issues, please reopen or open a new ticket
